"""add trip revenue

Revision ID: 0389d9b4daee
Revises: b6a5d4680487
Create Date: 2026-10-08 17:20:38.438069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0389d9b4daee'
down_revision: Union[str, Sequence[str], None] = 'b6a5d4680487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('revenue', sa.Float(), nullable=False))
    op.alter_column('trips', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_column('trips', 'revenue')
    # ### end Alembic commands ###
