"""add vehicle document fields

Revision ID: 270f5341a579
Revises: 36cd40c36035
Create Date: 2026-10-08 11:46:02.401674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270f5341a579'
down_revision: Union[str, Sequence[str], None] = '36cd40c36035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_column('vehicle_documents', 'file_name')
    # ### end Alembic commands ###
