"""add audit log description

Revision ID: b6a5d4680487
Revises: 270f5341a579
Create Date: 2026-10-08 17:05:33.305594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6a5d4680487'
down_revision: Union[str, Sequence[str], None] = '270f5341a579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', mysql.JSON(), nullable=True))
    op.drop_column('audit_logs', 'description')
    # ### end Alembic commands ###
